version: '3.3'
services:
  db:
    container_name: database
    ports:
      - 5432:5432
    image: postgres
    environment:
      POSTGRES_PASSWORD: example
    restart: always
  bot:
      container_name: bot
      build: .
      volumes:
        - .:/src
      command: python main.py
      restart: always